spring:
    application:
        name: product
    datasource:
            type: com.zaxxer.hikari.HikariDataSource
            url: jdbc:h2:file:./target/h2db/db/product;DB_CLOSE_DELAY=-1
            username: product
            password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
jwt:
  secret: dev-key
  expiration: 3600000

